version: '2'
services:
    versushipster-app:
        image: versushipster
        external_links:
            - versushipster-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/versushipster
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    versushipster-postgresql:
        extends:
            file: postgresql.yml
            service: versushipster-postgresql
